apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/danielinclouds/cd-with-argo-env-dev.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}